import { state } from '../state.js';
import { canvas } from '../canvas.js';
import { saveSnapshot } from '../undo.js';
import { callHook } from '../tools/tool-manager.js';

// ─── Zuordnen-Modus ──────────────────────────────────────
export function startAssignMode(measureId) {
  endAssignMode(); // vorherigen Modus beenden
  const meas = state.measurements.find(m => m.id === measureId);
  if (!meas) return;
  state.assignModePipeId = measureId;
  state._refsSnapshot = [...(meas.refs || [])];
  // Alle anderen Rohre sperren
  canvas.getObjects().filter(o => o._pipeType && !o._pipePreview).forEach(o => {
    o.selectable = false; o.evented = false;
  });
  // Ref-Objekte aktivieren (klickbar machen)
  canvas.getObjects().filter(o => o._pipeRefId != null).forEach(o => {
    o.selectable = true; o.evented = true;
  });
  const hint = document.getElementById('status-hint');
  if (hint) hint.textContent = 'Referenzen anklicken zum Zuordnen · Enter = Bestätigen · Esc = Abbrechen';
  callHook('updatePipeLegend');
  callHook('updatePipePanel');
}

export function endAssignMode() {
  state.assignModePipeId = null;
  state._refsSnapshot = null;
  // Rohre wieder freigeben
  canvas.getObjects().filter(o => o._pipeType && !o._pipePreview).forEach(o => {
    o.selectable = true; o.evented = true;
  });
  const hint = document.getElementById('status-hint');
  if (hint) hint.textContent = '';
  callHook('updatePipeLegend');
  callHook('updatePipePanel');
}

export function confirmAssignMode() {
  const measureId = state.assignModePipeId;
  endAssignMode();
  if (measureId != null) {
    callHook('renderDimLinesForPipe', measureId);
    saveSnapshot();
  }
}

export function cancelAssignMode() {
  const meas = state.measurements.find(m => m.id === state.assignModePipeId);
  if (meas && state._refsSnapshot) meas.refs = state._refsSnapshot;
  endAssignMode();
}

export function toggleRefAssignment(refId) {
  const meas = state.measurements.find(m => m.id === state.assignModePipeId);
  if (!meas) return;
  if (!meas.refs) meas.refs = [];
  const idx = meas.refs.indexOf(refId);
  if (idx === -1) meas.refs.push(refId);
  else meas.refs.splice(idx, 1);
  callHook('updatePipeLegend');
  callHook('updatePipePanel');
}

// Direkte Zuordnung per Checkbox — ohne modalen Assign-Modus
export function directToggleRef(measureId, refId, checked) {
  const meas = state.measurements.find(m => m.id === measureId);
  if (!meas) return;
  if (!meas.refs) meas.refs = [];
  if (checked && !meas.refs.includes(refId)) {
    meas.refs.push(refId);
  } else if (!checked) {
    const idx = meas.refs.indexOf(refId);
    if (idx !== -1) meas.refs.splice(idx, 1);
  }
  callHook('renderDimLinesForPipe', measureId);
  callHook('updatePipeLegend');
  callHook('updatePipePanel');
  saveSnapshot();
}

// Expose for inline onclick handlers generated by pipe.js (updatePipePanel)
window.directToggleRef = directToggleRef;
